/* This file has general constants declarations */
export const ACCESS_TOKEN_KEY = 'access_token'

export const PROTECTED_URLS = ['/dashboard']

export const ADDITIONAL = {
  LEADS: {
    SURVEY_IMAGE_LABELS: [
      "Do not use photo",
      "Old boiler and its pipework",
      "Old dataplate including back boiler",
      "Old flu",
      "Old filter",
      "Gas meter",
      "Electric meter",
      "Eletric meter fuse box",
      "Floor plan",
      "EST form",
      "EPC form",
      "Survey form",
      "Proof of ownership",
      "Proof of benefit",
      "Proof of address or utility bill",
      "Relationship declaration",
      "Bedroom picture",
      "Kitchen picture",
      "Living room picture",
      "Conservity",
      "Bathroom picture",
      "Extractor fan",
      "Hallway",
      "Cavity wall evidence",
      "Wall thickness picture",
      "All radiator picture",
      "TRV pictures",
      "Front elevation",
      "Back elevation",
      "Side elevation picture",
      "Cylinder Picture",
      "Evidence of secondary heating",
      "Programmer and room thermostats",
      "Loft pictures",
      "Loft measurement",
      "Picture of windows",
      "Windows thickness",
      "Evidence of ventilation",
      "Survey coordinates",
      "Extras"
    ],
    INSTALLATION_IMAGE_LABELS: [
      'Do not use photo',
      'Old Heating System',
      'Old Tank Picture without insulation',
      'Old boiler dataplate',
      'Side of boiler ( No dataplate available )',
      'Picture of old boiler',
      'Picture of old dataplate',
      'Picture of old flue',
      'Picture of new boiler',
      'Picture of new dataplate',
      'Picture of new flue',
      'Picture of Condensate Pipe ( Start to End must be Insulated )',
      'PRV ( it must be bent towards the wall and sealed )',
      'Gas Meter Pic with Earth Bonding Wire',
      'Picture of Electic Meter and Electric Fuse Box',
      'Picture of Electric Fuse Box',
      'Empty Walls with Brackets installed where New Radiators are going to be Installed',
      'Radiator picture',
      'Bypass radiator picture',
      'Picture of Old TRV',
      'Picture of NO TRV',
      'Picture of New TRV',
      'New TTZC covering 80% of house',
      'Benchmark Form Fully Filled',
      'Picture of Gas Safe Certificate',
      'Heating Control Device',
      'Receiver',
      'Fuse spur',
      'Clipped wire',
      'Picture of Filter Fitted',
      'Insulated pipe work picture',
      'Picture of Alarm System',
      'New radiator empty wall picture',
      'New Location Picture',
      'Old boiler removed wall picture',
      'New boiler empty wall',
      'New boiler in situ',
      'New boiler surrounding',
      'Boiler Front side sticker picture with Security Code for ( Potterton Baxi and Main Boiler )',
      'Extras'
    ]
  }
}
