/* This file has general constants declarations */
export const ACCESS_TOKEN_KEY = 'access_token'

export const PROTECTED_URLS = ['/dashboard']

export const ADDITIONAL = {
  LEADS: {
    SURVEY_IMAGE_LABELS: [
      "Do not use photo",
      "Old boiler and its pipework",
      "Old dataplate including back boiler",
      "Old flu",
      "Old filter",
      "Gas meter",
      "Electric meter",
      "Eletric meter fuse box",
      "Floor plan",
      "EST form",
      "EPC form",
      "Survey form",
      "Proof of ownership",
      "Proof of benefit",
      "Proof of address or utility bill",
      "Relationship declaration",
      "Bedroom picture",
      "Kitchen picture",
      "Living room picture",
      "Conservity",
      "Bathroom picture",
      "Extractor fan",
      "Hallway",
      "Cavity wall evidence",
      "Wall thickness picture",
      "All radiator picture",
      "TRV pictures",
      "Front elevation",
      "Back elevation",
      "Side elevation picture",
      "Cylinder Picture",
      "Evidence of secondary heating",
      "Programmer and room thermostats",
      "Loft pictures",
      "Loft measurement",
      "Picture of windows",
      "Windows thickness",
      "Evidence of ventilation",
      "Survey coordinates",
      "Extras"
    ],
    INSTALLATION_IMAGE_LABELS: [
      'Do not use photo',
      'Old Heating System',
      'Old data plate',
      'Old flue',
      'Old boiler',
      'Picture of new boiler',
      'Empty wall for boiler',
      'New data plate',
      'Picture of New flue',
      'Condensate pipe',
      'PRV',
      'Gas meter',
      'Electric meter & Electric Fuse box',
      'Empty wall for radiator',
      'New Radiator',
      'Radiators',
      'NO TRV',
      'New TRV',
      'Gas safe certificate',
      'Benchmark form',
      'Heating control device',
      'CMA (Carbon Monoxide Alarm)',
      'Receiver',
      'Fuse spur',
      'Filter',
      'Tank without insulation or jacket',
      'BOILER front side sticker',
      'Extras'
    ]
  }
}
